<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">{{ $vendor->supplier_no }}</p><h1 class="text-2xl font-bold text-[#071a3b]">{{ $vendor->company_name }}</h1><p class="mt-1 text-sm text-slate-500">{{ str($vendor->category)->replace('_', ' ')->headline() }} supplier</p></div>@can('vendors.manage')<a href="{{ route('vendors.edit', $vendor) }}" class="inline-flex h-11 items-center justify-center rounded-xl bg-blue-600 px-4 text-sm font-bold text-white">Edit supplier</a>@endcan</div>
    </x-slot>

    <div class="space-y-5">
        @if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{{ session('status') }}</div>@endif

        <div class="grid gap-5 xl:grid-cols-[1fr_360px]">
            <div class="space-y-5">
                <section class="erp-card p-5"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Registration status</p><span class="mt-2 inline-flex rounded-full {{ $vendor->status === 'active' ? 'bg-emerald-50 text-emerald-700' : ($vendor->status === 'inactive' ? 'bg-slate-100 text-slate-600' : 'bg-amber-50 text-amber-700') }} px-3 py-1 text-sm font-bold">{{ str($vendor->status)->replace('_', ' ')->headline() }}</span></div><div class="text-right"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Contact</p><p class="mt-2 font-bold text-[#071a3b]">{{ $vendor->contact_person ?: '-' }}</p><p class="mt-1 text-sm text-slate-500">{{ $vendor->mobile_no ?: $vendor->email ?: '-' }}</p></div></div></section>
                <section class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Company and payment details</h2><dl class="mt-5 grid gap-4 md:grid-cols-2 text-sm"><div><dt class="font-bold text-slate-400">Legal name</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->legal_name ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">Email</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->email ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">Trade licence</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->trade_license_no ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">Licence expiry</dt><dd class="mt-1 font-bold {{ $vendor->trade_license_expiry_date?->isPast() ? 'text-rose-600' : 'text-[#071a3b]' }}">{{ $vendor->trade_license_expiry_date?->format('M d, Y') ?? '-' }}</dd></div><div><dt class="font-bold text-slate-400">TRN</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->tax_registration_no ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">Payment terms</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->payment_terms ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">Bank</dt><dd class="mt-1 font-bold text-[#071a3b]">{{ $vendor->bank_name ?: '-' }}</dd></div><div><dt class="font-bold text-slate-400">IBAN</dt><dd class="mt-1 break-all font-bold text-[#071a3b]">{{ $vendor->iban ?: '-' }}</dd></div></dl><div class="mt-5 border-t border-slate-100 pt-4"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Address</p><p class="mt-2 whitespace-pre-line text-sm text-slate-600">{{ $vendor->address ?: '-' }}</p></div>@if($vendor->notes)<div class="mt-5 rounded-2xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase tracking-[0.16em] text-slate-400">Internal notes</p><p class="mt-2 whitespace-pre-line text-sm text-slate-600">{{ $vendor->notes }}</p></div>@endif</section>
            </div>

            <section class="erp-card p-5"><div><h2 class="text-lg font-bold text-[#071a3b]">Attached documents</h2><p class="mt-1 text-sm text-slate-500">Trade licence and other vendor compliance files.</p></div><div class="mt-5 space-y-3">@forelse($vendor->documents as $document)<a href="{{ route('vendors.documents.show', [$vendor, $document]) }}" class="block rounded-2xl border border-slate-200 p-4 transition hover:border-blue-200 hover:bg-blue-50"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-[#071a3b]">{{ $document->title ?: str($document->document_type)->replace('_', ' ')->headline() }}</p><p class="mt-1 text-xs text-slate-500">{{ $document->original_name }}</p></div><span class="text-blue-600">Download</span></div><div class="mt-3 flex justify-between text-xs text-slate-500"><span>{{ $document->document_number ?: 'No document number' }}</span><span class="{{ $document->expiry_date?->isPast() ? 'text-rose-600' : '' }}">{{ $document->expiry_date?->format('M d, Y') ?? 'No expiry' }}</span></div></a>@empty<p class="rounded-2xl border border-dashed border-slate-200 px-4 py-10 text-center text-sm text-slate-500">No documents uploaded yet.</p>@endforelse</div></section>
        </div>
    </div>
</x-app-layout>
