<x-app-layout>
<x-slot name="header"><div><p class="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">Accounting</p><h1 class="text-2xl font-bold text-[#071a3b]">Expenses</h1></div></x-slot>
<div class="space-y-6">@if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
    <section class="erp-card p-5">
        <div class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 class="text-lg font-bold text-[#071a3b]">Expense registry</h2><p class="mt-1 text-sm text-slate-500">Company, owner, tenant, agent, and operations expenses with receipt upload.</p></div>@can('expenses.manage')<a href="{{ route('expenses.create') }}" class="inline-flex h-11 items-center rounded-xl bg-blue-600 px-4 text-sm font-bold text-white">Add expense</a>@endcan</div>
        <form method="GET" class="mt-5 grid gap-3 lg:grid-cols-[1fr_170px_170px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Search expense..." class="erp-focus h-11 rounded-xl border border-slate-200 bg-[#f8faff] px-4 text-sm"><select name="type" class="erp-focus h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All types</option>@foreach(\App\Models\Expense::TYPES as $type)<option value="{{ $type }}" @selected(request('type') === $type)>{{ str($type)->replace('_',' ')->headline() }}</option>@endforeach</select><select name="expense_to_role" class="erp-focus h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">All targets</option>@foreach(\App\Models\Expense::TARGET_ROLES as $role)<option value="{{ $role }}" @selected(request('expense_to_role') === $role)>{{ str($role)->replace('_',' ')->headline() }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-4 text-sm font-bold text-white">Filter</button></form>
        <div class="mt-5 overflow-hidden rounded-2xl border border-slate-200"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500"><tr><th class="px-4 py-3">Expense</th><th class="px-4 py-3">Target</th><th class="px-4 py-3">Unit</th><th class="px-4 py-3">Date</th><th class="px-4 py-3">Amount</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse($expenses as $expense)<tr><td class="px-4 py-4"><div class="font-bold text-[#071a3b]">{{ $expense->expense_no }}</div><div class="text-xs text-slate-500">{{ $expense->name }} / {{ str($expense->type)->replace('_',' ')->headline() }}</div></td><td class="px-4 py-4 text-slate-600">{{ $expense->owner?->full_name ?? str($expense->expense_to_role)->replace('_',' ')->headline() }}</td><td class="px-4 py-4 text-slate-600">{{ $expense->unit ? $expense->unit->building->name.' / '.$expense->unit->unit_no : '-' }}</td><td class="px-4 py-4 text-slate-600">{{ $expense->incurred_on->format('M d, Y') }}</td><td class="px-4 py-4 font-bold text-[#071a3b]">AED {{ number_format((float)$expense->amount, 2) }}</td><td class="px-4 py-4"><div class="flex justify-end gap-2"><a href="{{ route('expenses.show', $expense) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">View</a>@can('expenses.manage')<a href="{{ route('expenses.edit', $expense) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">Edit</a>@endcan</div></td></tr>@empty<tr><td colspan="6" class="px-4 py-10 text-center text-sm text-slate-500">No expenses found.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $expenses->links() }}</div>
    </section>
</div>
</x-app-layout>
