<x-app-layout>
<x-slot name="header"><div><p class="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">Expense profile</p><h1 class="text-2xl font-bold text-[#071a3b]">{{ $expense->expense_no }}</h1></div></x-slot>
<div class="space-y-6">@if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
    <div class="grid gap-5 xl:grid-cols-[1fr_360px]">
        <section class="erp-card p-5">
            <div class="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.18em] text-blue-600">{{ str($expense->type)->replace('_',' ')->headline() }}</p><h2 class="mt-1 text-2xl font-black text-[#071a3b]">{{ $expense->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ str($expense->expense_to_role)->replace('_',' ')->headline() }} / {{ str($expense->association)->replace('_',' ')->headline() }}</p></div><div class="flex flex-wrap gap-2">@if($expense->receipt_path)<a href="{{ route('expenses.receipt', $expense) }}" target="_blank" class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">View receipt</a>@endif @can('expenses.manage')<a href="{{ route('expenses.edit', $expense) }}" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Edit</a>@endcan</div></div>
            <dl class="mt-6 grid gap-4 md:grid-cols-4"><div class="rounded-2xl bg-slate-50 p-4"><dt class="text-xs font-bold uppercase text-slate-400">Amount</dt><dd class="font-bold text-[#071a3b]">AED {{ number_format((float)$expense->amount, 2) }}</dd></div><div class="rounded-2xl bg-slate-50 p-4"><dt class="text-xs font-bold uppercase text-slate-400">Date</dt><dd class="font-bold text-[#071a3b]">{{ $expense->incurred_on->format('M d, Y') }}</dd></div><div class="rounded-2xl bg-slate-50 p-4"><dt class="text-xs font-bold uppercase text-slate-400">Owner</dt><dd class="font-bold text-[#071a3b]">{{ $expense->owner?->full_name ?? '-' }}</dd></div><div class="rounded-2xl bg-slate-50 p-4"><dt class="text-xs font-bold uppercase text-slate-400">Unit</dt><dd class="font-bold text-[#071a3b]">{{ $expense->unit ? $expense->unit->building->name.' / '.$expense->unit->unit_no : '-' }}</dd></div></dl>
            @if($expense->notes)<div class="mt-5 rounded-2xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{{ $expense->notes }}</div>@endif
        </section>
        <aside class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Accounting impact</h2><div class="mt-4 space-y-3 text-sm text-slate-600"><p class="rounded-2xl bg-blue-50 p-4">Owner-linked expenses appear in owner account statements.</p><p class="rounded-2xl bg-slate-50 p-4">Company expenses remain in internal reports.</p></div></aside>
    </div>
</div>
</x-app-layout>
