<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $ticket->ticket_no }} - Pattern Support</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#eef3f9] text-[#071a3b]">
<main class="mx-auto flex min-h-screen max-w-4xl flex-col px-3 py-4 md:px-6 md:py-8">
    <header class="rounded-t-[2rem] bg-[#061a38] p-5 text-white"><div class="flex items-center justify-between gap-3"><div class="flex items-center gap-3"><img src="{{ asset('brand/pattern-logo.jpeg') }}" class="h-12 w-44 rounded-xl bg-white object-contain p-2" alt="Pattern"><div><p class="text-xs font-black uppercase tracking-[0.16em] text-blue-300">{{ $ticket->ticket_no }}</p><h1 class="mt-1 font-black">{{ $ticket->subject }}</h1></div></div><span class="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-black"><span class="h-2 w-2 rounded-full bg-emerald-400"></span>{{ str($ticket->status)->replace('_',' ')->headline() }}</span></div></header>
    @if(session('status'))<div class="border-x border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{{ session('status') }}</div>@endif
    <section class="flex min-h-[65vh] flex-1 flex-col border-x border-slate-200 bg-white">
        <div class="flex-1 space-y-3 overflow-y-auto bg-[#eef3f9] p-4 md:p-6" data-public-messages data-message-count="{{ $ticket->messages->count() }}">
            @foreach($ticket->messages as $message)
                @php($staff = in_array($message->sender_type,['staff','bot'],true))
                <div class="flex {{ $staff ? 'justify-start' : 'justify-end' }}"><div class="max-w-[88%] rounded-[1.4rem] px-4 py-3 shadow-sm {{ $staff ? ($message->sender_type==='bot'?'border border-violet-100 bg-violet-50':'bg-white') : 'bg-blue-600 text-white' }}"><p class="text-[10px] font-black uppercase tracking-[0.12em] opacity-60">{{ $message->sender_name ?: str($message->sender_type)->headline() }}</p><p class="mt-1 whitespace-pre-line text-sm leading-6">{{ $message->body }}</p>@foreach($message->attachments as $attachment)<a href="{{ route('support.public.attachment', [$ticket,$token,$attachment]) }}" class="mt-2 block rounded-xl bg-white/80 px-3 py-2 text-xs font-bold text-blue-700">{{ $attachment->original_name }}</a>@endforeach<p class="mt-1 text-right text-[9px] opacity-50">{{ $message->created_at->format('M d, H:i') }}</p></div></div>
            @endforeach
        </div>
        <form method="POST" action="{{ route('support.public.reply', [$ticket,$token]) }}" enctype="multipart/form-data" class="border-t border-slate-200 p-3 md:p-4">@csrf<div class="flex items-end gap-2"><label class="grid h-11 w-11 shrink-0 cursor-pointer place-items-center rounded-xl border border-slate-200 text-xl text-slate-500">+<input type="file" name="attachment" class="sr-only"></label><textarea name="body" rows="2" class="erp-focus min-w-0 flex-1 resize-none rounded-2xl border border-slate-200 px-4 py-3 text-sm" placeholder="Type your reply..." required></textarea><button class="h-11 rounded-xl bg-blue-600 px-5 text-sm font-black text-white">Send</button></div></form>
    </section>
    <footer class="rounded-b-[2rem] border border-slate-200 bg-white p-4 text-center text-xs text-slate-500">Keep this private link to return to your conversation. Do not share it publicly.</footer>
</main><script>setInterval(async()=>{const box=document.querySelector('[data-public-messages]');const input=document.querySelector('textarea[name="body"]');if(!box||(input&&input.value.trim()))return;const response=await fetch('{{ route('support.public.messages',[$ticket,$token]) }}',{headers:{'Accept':'application/json'}});if(response.ok){const messages=await response.json();if(messages.length>Number(box.dataset.messageCount||0))window.location.reload();}},6000);</script></body></html>
