<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Pattern Support Center</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#eef3f9] text-[#071a3b]">
<main class="mx-auto grid min-h-screen max-w-6xl gap-8 px-4 py-8 lg:grid-cols-[380px_1fr] lg:items-center">
    <section class="rounded-[2rem] bg-[#061a38] p-8 text-white shadow-2xl"><img src="{{ asset('brand/pattern-logo.jpeg') }}" class="h-14 w-64 rounded-xl bg-white object-contain p-2" alt="Pattern"><p class="mt-10 text-xs font-black uppercase tracking-[0.2em] text-blue-300">Public Support Center</p><h1 class="mt-3 text-4xl font-black tracking-[-0.05em]">Talk to the right team without losing context.</h1><p class="mt-4 text-sm leading-7 text-blue-100/80">Start a live chat or ticket. Existing customers can add their booking or payment reference so the team can link the correct records securely.</p><div class="mt-8 space-y-3 text-sm"><p class="rounded-2xl bg-white/10 p-4">Live chat and automatic help replies</p><p class="rounded-2xl bg-white/10 p-4">Booking, payment, maintenance, payout, and documents</p><p class="rounded-2xl bg-white/10 p-4">Secure link to return and continue later</p></div></section>
    <section class="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl md:p-8">
        <div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[0.18em] text-blue-600">Start conversation</p><h2 class="mt-1 text-2xl font-black">How can we help?</h2></div><span class="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-black text-emerald-700"><span class="h-2 w-2 rounded-full bg-emerald-400"></span>Support available</span></div>
        @if($errors->any())<div class="mt-5 rounded-2xl bg-rose-50 p-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('support.public.store') }}" enctype="multipart/form-data" class="mt-6 grid gap-4 md:grid-cols-2">@csrf
            <div class="md:col-span-2"><p class="mb-2 text-sm font-black">Are you new or existing?</p><div class="grid grid-cols-2 gap-3"><label class="rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm font-bold"><input type="radio" name="requester_type" value="existing" class="mr-2" checked>Existing customer</label><label class="rounded-2xl border border-slate-200 p-4 text-sm font-bold"><input type="radio" name="requester_type" value="new" class="mr-2">New customer</label></div></div>
            <select name="requester_role" class="erp-focus h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm" required><option value="">Your role</option>@foreach($roles as $role)<option>{{ $role }}</option>@endforeach</select>
            <select name="support_category_id" class="erp-focus h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Support category</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select>
            <input name="requester_name" value="{{ old('requester_name') }}" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Full name" required>
            <input name="requester_email" type="email" value="{{ old('requester_email') }}" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Email" required>
            <input name="requester_mobile" value="{{ old('requester_mobile') }}" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Mobile / WhatsApp">
            <select name="priority" class="erp-focus h-12 rounded-xl border border-slate-200 bg-white px-3 text-sm">@foreach(\App\Models\SupportTicket::PRIORITIES as $priority)<option value="{{ $priority }}">{{ str($priority)->headline() }} priority</option>@endforeach</select>
            <input name="booking_reference" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Booking no, if existing">
            <input name="payment_reference" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm" placeholder="Payment/reference no, if applicable">
            <input name="subject" class="erp-focus h-12 rounded-xl border border-slate-200 px-3 text-sm md:col-span-2" placeholder="Short subject" required>
            <textarea name="description" rows="5" class="erp-focus rounded-xl border border-slate-200 px-3 py-3 text-sm md:col-span-2" placeholder="Write your message..." required>{{ old('description') }}</textarea>
            <label class="flex cursor-pointer items-center justify-center rounded-xl border-2 border-dashed border-blue-100 bg-blue-50 px-4 py-4 text-sm font-black text-blue-700 md:col-span-2">Attach image or document<input type="file" name="attachment" class="sr-only"></label>
            <button class="rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-black text-white md:col-span-2">Start support conversation</button>
        </form>
    </section>
</main></body></html>
