<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="theme-color" content="#071a3b">
    <title>{{ $booking->booking_no }} · Booking Confirmation</title>
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600,700,800,900&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen bg-slate-100 font-sans text-slate-700 antialiased">
    @php
        $nights = $booking->check_in_date && $booking->check_out_date ? $booking->check_in_date->diffInDays($booking->check_out_date) : null;
        $charges = [
            ['Accommodation rent', $booking->rent_amount, false],
            ['VAT 5% on rent', $booking->vat_amount, false],
            ['Refundable security deposit', $booking->deposit_amount, true],
            ['DTCM tourism fee', $booking->dtcm_fee, false],
            ['Cleaning fee', $booking->cleaning_fee, false],
            ['Agency fee', $booking->agency_fee, false],
        ];
    @endphp

    <header class="sticky top-0 z-30 border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur">
        <div class="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8">
            <img src="{{ asset('brand/pattern-logo.jpeg') }}" alt="Pattern Vacation Homes Rental" class="h-12 w-auto object-contain">
            <div class="flex items-center gap-2">
                <span class="hidden rounded-full px-3 py-1.5 text-xs font-black sm:inline-flex {{ $booking->confirmation_signed_at ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $booking->confirmation_signed_at ? 'Signed & accepted' : 'Not signed - awaiting signature' }}</span>
                <a href="{{ route('booking-confirmations.pdf', [$booking, $token]) }}" target="_blank" class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-black text-[#071a3b] hover:bg-slate-50">View PDF</a>
            </div>
        </div>
    </header>

    <main class="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8 lg:py-10">
        @if(session('status'))<div class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 px-5 py-4 text-sm font-bold text-emerald-700">{{ session('status') }}</div>@endif
        @if($errors->any())<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm font-bold text-rose-700">{{ $errors->first() }}</div>@endif

        <article class="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-xl shadow-slate-200/70">
            <section class="relative overflow-hidden bg-[#071a3b] px-6 py-9 text-white sm:px-10 lg:px-12">
                <div class="absolute -right-24 -top-32 h-80 w-80 rounded-full border border-blue-400/20"></div><div class="absolute right-16 top-8 h-32 w-32 rounded-full bg-blue-600/20 blur-3xl"></div>
                <div class="relative flex flex-col justify-between gap-8 md:flex-row md:items-end">
                    <div><p class="text-[11px] font-black uppercase tracking-[0.24em] text-blue-300">Official booking confirmation</p><h1 class="mt-3 text-3xl font-black tracking-[-0.04em] sm:text-4xl">{{ $booking->booking_no }}</h1><p class="mt-3 text-sm text-blue-100/75">Pattern Vacation Homes Rental · {{ str($booking->booking_type)->replace('_',' ')->headline() }}</p></div>
                    <div class="rounded-2xl border border-white/10 bg-white/[0.06] px-5 py-4 md:text-right"><p class="text-[10px] font-bold uppercase tracking-[0.18em] text-blue-200/70">Booking value</p><p class="mt-1 text-2xl font-black">AED {{ number_format((float)$booking->total_amount,2) }}</p><p class="mt-1 text-xs text-blue-100/60">Including VAT and refundable deposit</p></div>
                </div>
            </section>

            <div class="grid lg:grid-cols-[1fr_330px]">
                <div class="space-y-8 p-6 sm:p-10 lg:p-12">
                    <section><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-xs font-black text-blue-600">01</span><div><h2 class="text-lg font-black text-[#071a3b]">Stay and property details</h2><p class="text-xs text-slate-500">Confirmed accommodation and schedule.</p></div></div>
                        <dl class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Property',$booking->unit->building?->name],['Unit','Unit '.$booking->unit->unit_no],['Check-in',$booking->check_in_date?->format('D, M d, Y').' · '.($booking->check_in_time ?: 'Time to be advised')],['Check-out',$booking->check_out_date?->format('D, M d, Y').' · '.($booking->check_out_time ?: 'Time to be advised')],['Stay length',$nights !== null ? $nights.' night'.($nights===1?'':'s') : '—'],['Guests',$booking->guest_count.' guest'.($booking->guest_count==1?'':'s')],['Booking source',$booking->source ?: 'Direct'],['Status',str($booking->booking_status)->replace('_',' ')->headline()]] as [$label,$value])<div class="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><dt class="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">{{ $label }}</dt><dd class="mt-1.5 text-sm font-black leading-5 text-[#071a3b]">{{ $value }}</dd></div>@endforeach</dl>
                    </section>

                    <section class="border-t border-slate-100 pt-8"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-xs font-black text-blue-600">02</span><div><h2 class="text-lg font-black text-[#071a3b]">Guest information</h2><p class="text-xs text-slate-500">Primary guest responsible for this booking.</p></div></div><dl class="mt-5 grid gap-3 sm:grid-cols-3"><div class="rounded-2xl border border-slate-200 p-4"><dt class="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Full name</dt><dd class="mt-1.5 font-black text-[#071a3b]">{{ $booking->tenant->full_name }}</dd></div><div class="rounded-2xl border border-slate-200 p-4"><dt class="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Mobile</dt><dd class="mt-1.5 font-black text-[#071a3b]">{{ $booking->tenant->mobile_no ?: 'Not provided' }}</dd></div><div class="rounded-2xl border border-slate-200 p-4"><dt class="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Email</dt><dd class="mt-1.5 break-all font-black text-[#071a3b]">{{ $booking->tenant->email ?: 'Not provided' }}</dd></div></dl></section>

                    <section class="border-t border-slate-100 pt-8"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-xs font-black text-blue-600">03</span><div><h2 class="text-lg font-black text-[#071a3b]">Charges and payment summary</h2><p class="text-xs text-slate-500">VAT is calculated only on accommodation rent.</p></div></div><div class="mt-5 overflow-hidden rounded-2xl border border-slate-200"><table class="w-full text-left"><thead class="bg-slate-50 text-[10px] font-black uppercase tracking-[0.15em] text-slate-400"><tr><th class="px-5 py-3">Description</th><th class="px-5 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($charges as [$label,$amount,$refundable])<tr><td class="px-5 py-3.5 text-sm font-bold text-slate-600">{{ $label }} @if($refundable)<span class="ml-2 rounded-full bg-violet-50 px-2 py-1 text-[9px] font-black uppercase text-violet-700">Refundable</span>@endif</td><td class="px-5 py-3.5 text-right text-sm font-black text-[#071a3b]">AED {{ number_format((float)$amount,2) }}</td></tr>@endforeach</tbody><tfoot class="bg-[#071a3b] text-white"><tr><th class="px-5 py-4 text-sm font-black">Total booking value</th><th class="px-5 py-4 text-right text-lg font-black">AED {{ number_format((float)$booking->total_amount,2) }}</th></tr></tfoot></table></div>
                        @if(!empty($booking->rental_periods))<div class="mt-4 rounded-2xl bg-blue-50 p-4"><p class="text-xs font-black uppercase tracking-[0.14em] text-blue-700">Rental schedule</p><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($booking->rental_periods as $period)<div class="flex justify-between rounded-xl bg-white px-3 py-2 text-xs"><span class="font-bold text-slate-500">{{ !empty($period['period_start']) ? \Carbon\Carbon::parse($period['period_start'])->format('M d, Y') : 'Rental period' }}{{ !empty($period['period_end']) ? ' – '.\Carbon\Carbon::parse($period['period_end'])->format('M d, Y') : '' }}</span><span class="font-black text-[#071a3b]">AED {{ number_format((float)($period['rent_amount'] ?? 0),2) }}</span></div>@endforeach</div></div>@endif
                    </section>

                    <section class="border-t border-slate-100 pt-8"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-xs font-black text-blue-600">04</span><div><h2 class="text-lg font-black text-[#071a3b]">Booking terms and acknowledgement</h2><p class="text-xs text-slate-500">Please review before accepting.</p></div></div><div class="mt-5 grid gap-3 text-sm leading-6 text-slate-600 sm:grid-cols-2"><div class="rounded-2xl bg-slate-50 p-4"><p class="font-black text-[#071a3b]">Guest responsibility</p><p class="mt-1">The primary guest is responsible for the unit, occupants, keys, access devices, and compliance with building and community rules during the stay.</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="font-black text-[#071a3b]">Security deposit</p><p class="mt-1">The security deposit is refundable after checkout inspection, less approved damage, missing items, unpaid charges, or other documented deductions.</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="font-black text-[#071a3b]">Check-in requirement</p><p class="mt-1">Check-in is completed after required guest documents, payment confirmation, and applicable DTCM registration are completed.</p></div><div class="rounded-2xl bg-slate-50 p-4"><p class="font-black text-[#071a3b]">Booking changes</p><p class="mt-1">Extensions, early checkout, cancellation, and refunds remain subject to written company approval and the applicable booking policy.</p></div></div>@if($booking->notes)<div class="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-4"><p class="text-xs font-black uppercase tracking-[0.14em] text-amber-700">Special booking notes</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-amber-900">{{ $booking->notes }}</p></div>@endif</section>

                    <section id="signature" class="scroll-mt-24 border-t border-slate-100 pt-8"><div class="flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl {{ $booking->confirmation_signed_at ? 'bg-emerald-50 text-emerald-700' : 'bg-blue-50 text-blue-600' }} text-xs font-black">05</span><div><h2 class="text-lg font-black text-[#071a3b]">Guest acceptance and signature</h2><p class="text-xs text-slate-500">Electronic signature is recorded with date, time, and IP address.</p></div></div>
                        @if(!$booking->confirmation_signed_at)
                            <form method="POST" action="{{ route('booking-confirmations.sign.store',[$booking,$token]) }}" class="mt-5 rounded-3xl border border-blue-100 bg-blue-50/60 p-4 sm:p-6">@csrf<div class="grid gap-3 sm:grid-cols-2"><label class="text-xs font-black text-slate-600">Signer full name<input name="signed_by" value="{{ old('signed_by',$booking->tenant->full_name) }}" required class="erp-focus mt-1.5 h-12 w-full rounded-xl border-blue-100 bg-white px-3 text-sm"></label><label class="text-xs font-black text-slate-600">Booking reference<input value="{{ $booking->booking_no }}" readonly class="mt-1.5 h-12 w-full rounded-xl border-slate-200 bg-slate-100 px-3 text-sm font-bold text-slate-500"></label></div><input type="hidden" name="signature_text" value="{{ old('signature_text',$booking->tenant->full_name) }}"><div class="mt-4"><x-signature-pad input-name="signature_data" input-id="tenant_booking_signature" label="Draw guest signature" /></div><label class="mt-4 flex items-start gap-3 rounded-2xl bg-white p-4 text-sm leading-6 text-slate-600"><input type="checkbox" name="accepted_terms" value="1" required class="mt-1 rounded border-slate-300 text-blue-600"> <span>I confirm that I have reviewed this complete booking confirmation, the charges, and the terms above, and I accept them electronically.</span></label><button class="mt-4 w-full rounded-xl bg-blue-600 px-5 py-3.5 text-sm font-black text-white shadow-lg shadow-blue-600/20">Accept and sign booking confirmation</button></form>
                        @else
                            <div class="mt-5 grid gap-4 rounded-3xl border border-emerald-200 bg-emerald-50/70 p-5 sm:grid-cols-[1fr_260px] sm:p-6"><div><span class="inline-flex rounded-full bg-emerald-600 px-3 py-1 text-[10px] font-black uppercase tracking-[0.14em] text-white">Signed & accepted</span><h3 class="mt-3 text-xl font-black text-[#071a3b]">{{ $booking->confirmation_signed_by }}</h3><p class="mt-2 text-sm leading-6 text-emerald-800">Signed electronically on {{ $booking->confirmation_signed_at->format('M d, Y \a\t H:i') }}.</p><p class="mt-1 text-xs text-emerald-700">Audit IP: {{ $booking->confirmation_signed_ip ?: 'Not recorded' }}</p></div><div class="rounded-2xl border border-emerald-200 bg-white p-3"><p class="text-[10px] font-black uppercase tracking-[0.14em] text-slate-400">Guest signature</p>@if($booking->confirmation_signature_data)<img src="{{ $booking->confirmation_signature_data }}" alt="Signature of {{ $booking->confirmation_signed_by }}" class="mt-2 h-28 w-full object-contain">@else<p class="mt-5 text-center text-sm font-bold text-slate-400">Signature recorded</p>@endif</div></div>
                        @endif
                    </section>
                </div>

                <aside class="border-t border-slate-200 bg-slate-50 p-6 lg:border-l lg:border-t-0 lg:p-7"><div class="space-y-4 lg:sticky lg:top-24"><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">Document status</p><div class="mt-3 flex items-center gap-3"><span class="h-3 w-3 rounded-full {{ $booking->confirmation_signed_at ? 'bg-emerald-500' : 'bg-amber-500' }}"></span><p class="font-black text-[#071a3b]">{{ $booking->confirmation_signed_at ? 'Signed and accepted' : 'Signature required' }}</p></div><p class="mt-2 text-xs leading-5 text-slate-500">Reference {{ $booking->booking_no }}</p></div><div class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-[10px] font-black uppercase tracking-[0.16em] text-slate-400">At a glance</p><dl class="mt-3 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Property</dt><dd class="text-right font-black text-[#071a3b]">{{ $booking->unit->building?->name }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Unit</dt><dd class="font-black text-[#071a3b]">{{ $booking->unit->unit_no }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Guest</dt><dd class="text-right font-black text-[#071a3b]">{{ $booking->tenant->full_name }}</dd></div><div class="flex justify-between gap-4 border-t border-slate-100 pt-3"><dt class="text-slate-500">Total</dt><dd class="font-black text-[#071a3b]">AED {{ number_format((float)$booking->total_amount,2) }}</dd></div></dl></div>@if(!$booking->confirmation_signed_at)<a href="#signature" class="block rounded-xl bg-blue-600 px-5 py-3.5 text-center text-sm font-black text-white shadow-lg shadow-blue-600/20">Review and sign</a>@endif<a href="{{ route('booking-confirmations.pdf',[$booking,$token]) }}" target="_blank" class="block rounded-xl border border-slate-200 bg-white px-5 py-3 text-center text-sm font-black text-[#071a3b]">Open printable PDF</a><div class="rounded-2xl bg-[#071a3b] p-5 text-white"><p class="text-xs font-black">Need assistance?</p><p class="mt-2 text-xs leading-5 text-blue-100/70">Contact Pattern Vacation Homes Rental and quote booking {{ $booking->booking_no }}.</p></div></div></aside>
            </div>
        </article>
        <p class="py-6 text-center text-xs text-slate-400">© {{ date('Y') }} Pattern Vacation Homes Rental. Secure electronic booking confirmation.</p>
    </main>
</body>
</html>
