<div class="flex items-start justify-between gap-3"><div><p class="text-[11px] font-black uppercase tracking-[0.18em] text-blue-600">TT Lock API</p><h2 class="mt-1 text-xl font-black text-[#071a3b]">{{ $title }}</h2></div><button type="button" x-on:click="$dispatch('close')" class="rounded-xl bg-slate-100 px-3 py-2 text-sm font-black text-slate-600">Close</button></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2">
    <label class="text-xs font-black text-[#071a3b]">Group name<input name="name" value="{{ old('name', $setting?->name) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Primary account"></label>
    <label class="text-xs font-black text-[#071a3b]">Client ID<input name="client_id" value="{{ old('client_id', $setting?->client_id) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" required></label>
    <label class="text-xs font-black text-[#071a3b]">Client secret<input name="client_secret" value="{{ old('client_secret', $setting?->client_secret) }}" type="password" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" autocomplete="new-password" required></label>
    <label class="text-xs font-black text-[#071a3b]">Username<input name="username" value="{{ old('username', $setting?->username) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" required></label>
    <label class="text-xs font-black text-[#071a3b]">Password<input name="password" value="{{ old('password', $setting?->password) }}" type="password" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" autocomplete="new-password" required></label>
    <label class="text-xs font-black text-[#071a3b]">Redirect URI<input name="redirect_uri" value="{{ old('redirect_uri', $setting?->redirect_uri) }}" type="url" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="https://..."></label>
</div>
<label class="mt-4 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold text-[#071a3b]"><input type="hidden" name="is_active" value="0"><input name="is_active" value="1" type="checkbox" class="rounded border-slate-300 text-blue-600" @checked(old('is_active', $setting?->is_active ?? true))> Active credential group</label>
<div class="mt-6 flex justify-end gap-2"><button type="button" x-on:click="$dispatch('close')" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Cancel</button><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white">Save group</button></div>
