<div class="flex items-start justify-between gap-3"><div><p class="text-[11px] font-black uppercase tracking-[0.18em] text-blue-600">Lock inventory</p><h2 class="mt-1 text-xl font-black text-[#071a3b]">{{ $title }}</h2></div><button type="button" x-on:click="$dispatch('close')" class="rounded-xl bg-slate-100 px-3 py-2 text-sm font-black text-slate-600">Close</button></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    <label class="text-xs font-black text-[#071a3b]">API group<select name="tt_lock_setting_id" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">No credential group</option>@foreach($settings as $item)<option value="{{ $item->id }}" @selected(old('tt_lock_setting_id', $lock?->tt_lock_setting_id) == $item->id)>{{ $item->name }} / {{ $item->username }}</option>@endforeach</select></label>
    <label class="text-xs font-black text-[#071a3b]">Lock name<input name="lock_name" value="{{ old('lock_name', $lock?->lock_name) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" required></label>
    <label class="text-xs font-black text-[#071a3b]">TT Lock ID<input name="lock_id" value="{{ old('lock_id', $lock?->lock_id) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" required></label>
    <label class="text-xs font-black text-[#071a3b]">Alias / door<input name="lock_alias" value="{{ old('lock_alias', $lock?->lock_alias) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b]">Gateway ID<input name="gateway_id" value="{{ old('gateway_id', $lock?->gateway_id) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b]">MAC address<input name="mac_address" value="{{ old('mac_address', $lock?->mac_address) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b]">Battery %<input name="battery_level" value="{{ old('battery_level', $lock?->battery_level) }}" type="number" min="0" max="100" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b]">Signal strength<input name="signal_strength" value="{{ old('signal_strength', $lock?->signal_strength) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b]">Status<select name="status" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $lock?->status ?? 'active') === $status)>{{ str($status)->replace('_', ' ')->headline() }}</option>@endforeach</select></label>
    <label class="text-xs font-black text-[#071a3b] sm:col-span-2">Last synced<input name="last_synced_at" type="datetime-local" value="{{ old('last_synced_at', $lock?->last_synced_at?->format('Y-m-d\TH:i')) }}" class="erp-focus mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"></label>
    <label class="text-xs font-black text-[#071a3b] sm:col-span-2 lg:col-span-1">Notes<textarea name="notes" rows="2" class="erp-focus mt-2 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm">{{ old('notes', $lock?->notes) }}</textarea></label>
</div>
<div class="mt-6 flex justify-end gap-2"><button type="button" x-on:click="$dispatch('close')" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-black">Cancel</button><button class="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-black text-white">Save lock</button></div>
