@csrf
@if ($errors->any())<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><p class="font-bold">Please fix the highlighted fields.</p><ul class="mt-2 list-inside list-disc">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="grid gap-5 xl:grid-cols-[1fr_360px]"><div class="space-y-5">
<div class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Invoice details</h2><div class="mt-5 grid gap-4 md:grid-cols-2"><div><x-input-label for="booking_id" value="Booking" /><select id="booking_id" name="booking_id" class="erp-focus mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" required><option value="">Select booking</option>@foreach ($bookings as $option)<option value="{{ $option->id }}" @selected(old('booking_id', $invoice->booking_id ?? $booking?->id) == $option->id)>{{ $option->booking_no }} - {{ $option->tenant->full_name }} - {{ $option->unit->building->name }}/{{ $option->unit->unit_no }}</option>@endforeach</select></div><div><x-input-label for="status" value="Status" /><select id="status" name="status" class="erp-focus mt-1 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">@foreach (\App\Models\Invoice::STATUSES as $status)<option value="{{ $status }}" @selected(old('status', $invoice->status ?? 'sent') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div><div><x-input-label for="invoice_date" value="Invoice date" /><x-text-input id="invoice_date" name="invoice_date" type="date" class="mt-1 block w-full" :value="old('invoice_date', isset($invoice) ? $invoice->invoice_date?->format('Y-m-d') : now()->format('Y-m-d'))" /></div><div><x-input-label for="due_date" value="Due date" /><x-text-input id="due_date" name="due_date" type="date" class="mt-1 block w-full" :value="old('due_date', isset($invoice) ? $invoice->due_date?->format('Y-m-d') : now()->addDays(2)->format('Y-m-d'))" /></div></div></div>
<div class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Charges</h2><p class="mt-1 text-sm text-slate-500">VAT is calculated automatically as 5% of rent only.</p><div class="mt-5 grid gap-4 md:grid-cols-3">@php($source = $booking ?? null)@foreach (['rent_amount' => 'Rent', 'deposit_amount' => 'Deposit', 'dtcm_fee' => 'DTCM', 'cleaning_fee' => 'Cleaning', 'agency_fee' => 'Agency fee'] as $field => $label)<div><x-input-label :for="$field" :value="$label" /><x-text-input :id="$field" :name="$field" class="mt-1 block w-full" :value="old($field, $invoice->{$field} ?? $source?->{$field} ?? 0)" /></div>@endforeach</div><div class="mt-4 rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm font-bold text-blue-700">VAT preview: AED <span data-vat-preview>{{ number_format((float) (($invoice->vat_amount ?? null) ?: (($source?->rent_amount ?? 0) * 0.05)), 2) }}</span></div></div>
</div><div class="space-y-5"><div class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Payment behavior</h2><div class="mt-4 space-y-3 text-sm text-slate-600"><p class="rounded-2xl bg-blue-50 p-4">When fully paid, receipt is issued and emailed with check-in code.</p><p class="rounded-2xl bg-emerald-50 p-4">Booking becomes confirmed automatically.</p><p class="rounded-2xl bg-amber-50 p-4">DTCM check-in is prepared. Booking is checked in only after DTCM guest registration is completed.</p></div></div><div class="erp-card p-5"><h2 class="text-lg font-bold text-[#071a3b]">Notes</h2><textarea name="notes" rows="8" class="erp-focus mt-4 w-full rounded-xl border border-slate-200 px-3 py-2 text-sm">{{ old('notes', $invoice->notes ?? '') }}</textarea></div></div></div>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('invoices.index') }}" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-600">Cancel</a><x-primary-button>{{ $submitLabel }}</x-primary-button></div>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const rent = document.getElementById('rent_amount');
        const vatPreview = document.querySelector('[data-vat-preview]');
        if (!rent || !vatPreview) return;
        const update = () => {
            const value = Number.parseFloat(rent.value || '0') || 0;
            vatPreview.textContent = (value * 0.05).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
        };
        rent.addEventListener('input', update);
        update();
    });
</script>
