<x-app-layout>
<x-slot name="header"><div><p class="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">Owner agreements</p><h1 class="text-2xl font-bold text-[#071a3b]">Owner contracts</h1></div></x-slot>
<div class="space-y-6">
@if(session('status'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">{{ session('status') }}</div>@endif
<div class="erp-card p-5">
<div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 class="text-lg font-bold text-[#071a3b]">Property management contracts</h2><p class="mt-1 text-sm text-slate-500">Basic manual contract records based on the Pattern owner agreement format.</p></div>@can('owner-contracts.manage')<a href="{{ route('owner-contracts.create') }}" class="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white">Add contract</a>@endcan</div>
<div class="mt-5 overflow-hidden rounded-2xl border border-slate-200"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-[11px] font-bold uppercase tracking-[0.16em] text-slate-500"><tr><th class="px-4 py-3">Contract</th><th class="px-4 py-3">Owner / unit</th><th class="px-4 py-3">Fees</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-slate-100 bg-white">@forelse($contracts as $contract)<tr><td class="px-4 py-4"><div class="font-bold text-[#071a3b]">{{ $contract->contract_no }}</div><div class="text-xs text-slate-500">{{ $contract->contract_start_date?->format('M d, Y') ?? 'No start' }} - {{ $contract->contract_end_date?->format('M d, Y') ?? 'No end' }}</div></td><td class="px-4 py-4"><div class="font-bold text-[#071a3b]">{{ $contract->owner_name }}</div><div class="text-xs text-slate-500">{{ $contract->unit->building?->name }} / Unit {{ $contract->unit->unit_no }}</div></td><td class="px-4 py-4"><div class="font-bold text-[#071a3b]">{{ $contract->management_fee_percent }}%</div><div class="text-xs text-slate-500">Total AED {{ number_format((float) $contract->grand_total, 2) }}</div></td><td class="px-4 py-4"><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{{ str($contract->status)->headline() }}</span></td><td class="px-4 py-4 text-right"><a href="{{ route('owner-contracts.show', $contract) }}" class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-600">View</a></td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-slate-500">No contracts yet.</td></tr>@endforelse</tbody></table></div>
<div class="mt-5">{{ $contracts->links() }}</div>
</div></div>
</x-app-layout>
